project/myproject/OTS/urls.py
from django.urls import path
from OTS.views import *
app_name='OTS'

urlpatterns = [
    path('',welcome),
    path('new-candidate',CandidateRegistrationForm, name='registrationForm'),
    path('store-candidate',CandidateRegistration,name='storeCandidate'),
    path('login',loginView, name='login'),
    path('home',candidateHome, name='home'),
    path('test-paper',testPaper, name='testPaper'),
    path('calculate-result',calculateTestResult, name='calculateTest'),
    path('test-history',testResultHistory, name='testHistory'),
    path('result',showTestResult, name='result'),
    path('logout',logoutView, name='logout')

]

project/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('OTS/',include('OTS.urls')),
]

project/myproject/OTS/models.py
from django.db import models

# Create your models here.

class Candidate(models.Model):
    username=models.CharField(primary_key=True,max_length=20)
    password=models.CharField(null=False,max_length=20)
    name=models.CharField(null=False,max_length=30)
    test_attempted=models.IntegerField(default=0)
    points=models.FloatField(default=0.0)
    def __str__(self):
        return self.name

class Question(models.Model):
    qid=models.BigAutoField(primary_key=True,auto_created=True)
    que=models.TextField()
    a=models.CharField(max_length=255)
    b=models.CharField(max_length=255)
    c=models.CharField(max_length=255)
    d=models.CharField(max_length=255)
    ans=models.CharField(max_length=2)
    def __str__(self):
        return self.que
class Result(models.Model):
    resultid=models.BigAutoField(primary_key=True,auto_created=True)
    username=models.ForeignKey(Candidate,on_delete=models.CASCADE)
    date=models.DateField(auto_now=True)
    time=models.TimeField(auto_now=True)
    attempt=models.IntegerField()
    right=models.IntegerField()
    wrong=models.IntegerField()
    points=models.FloatField()
    def __str__(self):
        return self.resultid

project/myproject/OTS/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse,HttpResponseRedirect
from OTS.models import *
import random

# Create your views here.

def welcome(request):
    template=loader.get_template('welcome.html')
    return HttpResponse(template.render())
def CandidateRegistrationForm(request):
    res=render(request,'registration_Form.html')
    return res
def CandidateRegistration(request):
    if request.method=='POST':
        username=request.POST['username']
        # Check if The User Already Exists
        if(len(Candidate.objects.filter(username=username))):
            userStatus=1
        else:
            candidate=Candidate()
            candidate.username=username
            candidate.password=request.POST['password'] 
            candidate.name=request.POST['name']
            candidate.save()
            userStatus=2  
    else:
        userStatus=3 # Request Method is Not POST
    context={
        'userStatus':userStatus

    }   
    res=render(request,'registration.html',context)
    return res       
def loginView(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        candidate=Candidate.objects.filter(username=username,password=password)
        if len(candidate)==0:
            loginError="Invalid Username Or Password"
            res=render(request,'login.html',{'loginError':loginError})
        else:
            #Login Success
            request.session['username']=candidate[0].username
            request.session['name']=candidate[0].name
            res=HttpResponseRedirect("home") 
    else:
        res=render(request,'login.html')
    return res
def candidateHome(request):
    if 'name' not in request.session.keys():
        res=HttpResponseRedirect("login")
    else:
        res=render(request,'home.html')
    return res    

def testPaper(request):
    if 'name' not in request.session.keys():
        res=HttpResponseRedirect("login")
    #Fetch Question From DataBase Table
    n=int(request.GET['n'])
    question_pool=list(Question.objects.all())
    random.shuffle(question_pool)
    questions_list=question_pool[:n]
    context={'questions':questions_list}
    res=render(request,'test_paper.html',context)
    return res
def calculateTestResult(request):
    if 'name' not in request.session.keys():
        res=HttpResponseRedirect("login")
    total_attempt=0
    total_right=0
    total_wrong=0
    qid_list=[]
    for k in request.POST:
        if k.startswith('qno'):
            qid_list.append(int(request.POST[k]))
    for n in qid_list:
        question=Question.objects.get(qid=n)
        try:
            if question.ans==request.POST['q'+str(n)]:
                total_right+=1
            else:
                total_wrong+=1
            total_attempt+=1
        except:
            pass         
    points=(total_right-total_wrong)/len(qid_list)*10
    # Store Result in Result Table
    result=Result()
    result.username=Candidate.objects.get(username=request.session['username'])
    result.attempt=total_attempt
    result.right=total_right
    result.wrong=total_wrong
    result.points=points
    result.save()

    # Update Candidate Table
    candidate=Candidate.objects.get(username=request.session['username'])
    candidate.test_attempted+=1
    candidate.points=(candidate.points*(candidate.test_attempted-1)+points)/candidate.test_attempted
    candidate.save()
    return HttpResponseRedirect('result')

def testResultHistory(request):
    if 'name' not in request.session.keys():
        res=HttpResponseRedirect("login")
    candidate=Candidate.objects.filter(username=request.session['username'])
    results=Result.objects.filter(username_id=candidate[0].username)
    context={'candidate':candidate[0],'results':results}
    res=render(request,'candidate_history.html',context)
    return res
def showTestResult(request):
    if 'name' not in request.session.keys():
        res=HttpResponseRedirect("login")
    # Fetch Latest Result From Result Table
    result=Result.objects.filter(resultid=Result.objects.latest('resultid').resultid,username_id=request.session['username'])
    context={'result':result}
    res=render(request,'show_result.html',context)
    return res    
    
def logoutView(request):
    if 'name' in request.session.keys():
        del request.session['username']
        del request.session['name']
    return HttpResponseRedirect("login")









    

project/myproject/OTS/templates/candidate_history.html
{% extends 'main.html' %}

{% block title %} OTS - Candidate Result History {% endblock title %}
{% block top %}
<a href="{%url 'OTS:home' %}">Home</a>
<a href="{%url 'OTS:logout' %}">Logout</a>
{% endblock %}
{% block content %}
<div class="bgrep"></div>
<h1 class="head">Your Report Card</h1>
<p class="repo">Hi <span class="special">{{candidate.name}}</span> , 
    You Have Attempted In Total <span class="special"> {{candidate.test_attempted}}</span> Test And You Have Scored <span class="special">{{candidate.points}}</span> On The Scale Of 10.  </p>
<table>
    <tr>
        <th>Date</th>
        <th>Time</th>
        <th>Attempt</th>
        <th>Right</th>
        <th>Wrong</th>
        <th>Points</th>
    </tr>
    {% for r in results %}
    <tr>
        <td>{{r.date}}</td>
        <td>{{r.time}}</td>
        <td>{{r.attempt}}</td>
        <td>{{r.right}}</td>
        <td>{{r.wrong}}</td>
        <td>{{r.points}}</td>
    </tr>
    {% endfor %}
    
</table>
{% endblock %}

project/myproject/OTS/templates/home.html
{% extends 'main.html' %}

{% block title %} OTS - Candidate Home Page  {% endblock title %}
{% block top %}
<a href="{%url 'OTS:home' %}">Home</a>
<a href="{%url 'OTS:logout' %}">Logout</a>
{% endblock %}
{% block content %}
<div class="head">

<h1>Welcome {{request.session.name}}, To Your Home Page</h1>
</div>
<div class="bghome"></div>
<div class="button-link">
    <a href="{% url 'OTS:testPaper' %}?n=1">Test Of 1 Question</a>
</div>
<div class="button-link">
    <a href="{% url 'OTS:testPaper' %}?n=5">Test Of 5 Question</a>
</div>
<div class="button-link">
    <a href="{% url 'OTS:testPaper' %}?n=10">Test Of 10 Question</a>
</div>
<div class="button-link">
    <a href="{% url 'OTS:testPaper' %}?n=20">Test Of 20 Question</a>
</div>
<div class="button-link">
    <a href="{% url 'OTS:testHistory' %}">Test History</a>
</div>
{% endblock %}

project/myproject/OTS/templates/login.html
{% extends 'main.html' %}

{% block title %} OTS - Login Form {% endblock title %}
{% block top %}
<a href="{%url 'OTS:registrationForm' %}"> SignUp </a>

{% endblock %}
{% block content %}
<div class="bgloginform"></div>
<div class="all-forms">
    {% if loginError %}
        <div id="error">{{loginError}}</div>
    {% endif %}
    <form action="{% url 'OTS:login' %}" method="POST">
        {% csrf_token %}
        <div class="form-unit">
            <label for="username">Username</label><br>
            <input type="text" name="username"><br>
        </div>
        <div class="form-unit">
            <label for="password">Password</label><br>
            <input type="password" name="password"><br>
        </div>
        <div class="formunit">
            <input type="submit" value="Login">
            <input type="reset" value="Clear">
        </div>
    </form>
    <div class="newuser">
    New User <a href="{%url 'OTS:registrationForm' %}">Click Here</a>
    </div>
</div>
{% endblock %}

project/myproject/OTS/templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block titles %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'theme.css' %}">
    <link rel="stylesheet" href="{% static 'formstyle.css' %}">
    <link rel="stylesheet" href="{% static 'buttonstyle.css' %}">
</head>
<body>
    <div class="top">
        <div class="sitename"><h1> Online Testing System</h1></div>
        <div class="menu">
            {% block top %} {% endblock %}
         </div>
    </div>
    <div class="content">
        {% block content %} {% endblock %}

    </div>
</body>
</html>

project/myproject/OTS/templates/registration.html
{% extends 'main.html' %}

{% block title %} OTS-Registration Status{% endblock title %}
{% block top %}
<a href="{%url 'OTS:registrationForm' %}">New Candidate Registration</a>
<a href="{%url 'OTS:login' %}">Login</a>
{% endblock %}
{% block content %}
{% if userStatus == 1 %}
    <div class="userStatus">
        Sorry, username already exist, Please Try Different UserName.
        <a href="{%url 'OTS:registrationForm' %}">Back To Candidate Registration Form</a>
    </div>
{% elif userStatus == 2 %}   
    <div class="userStatus">
        Congratulations!!,User Created Successfully.
        <a href="{%url 'OTS:login' %}">Login</a>
    </div> 
{% elif userStatus == 3 %} 
<div class="userStatus">
    Oops!!,Improper Request.
    <a href="{%url 'OTS:registrationForm' %}">Login</a>
</div>   
{% endif %}
{% endblock %}

project/myproject/OTS/templates/registration_Form.html
{% extends 'main.html' %}

{% block title %} OTS-Registratin Form {% endblock title %}
{% block top %}

<a href="{%url 'OTS:login' %}">Login</a>
{% endblock %}
{% block content %}
<div class="bgsignupform"></div>
<div class="all-forms">
    <form action="{% url 'OTS:storeCandidate' %}" method="post">
        {% csrf_token %}
        <h1>Student SignUp</h1>
        <label for="username">Username</label><br>
        <input type="text" name="username"><br>
        <label for="password">Password</label><br>
        <input type="password" name="password"><br>
        <label for="name">Name</label><br>
        <input type="text" name="name"><br>
        <div class="button">
        <input type="Submit" value="Submit">
        <input type="reset" value="Clear">
    </div>


    </form>
    <div class="click">
    Already have an Account, <a href="{% url 'OTS:login' %}">Click Here</a>
</div>
</div>
{% endblock %}

project/myproject/OTS/templates/show_result.html
{% extends 'main.html' %}

{% block title %} OTS - Test Result {% endblock title %}
{% block top %}
<a href="{%url 'OTS:home' %}">Home</a>
<a href="{%url 'OTS:logout' %}">Logout</a>
{% endblock %}
{% block content %}
<h1 class="hed">Your Result</h1>
<table>
    <tr>
        <th>Date</th>
        <th>Time</th>
        <th>Attempt</th>
        <th>Right</th>
        <th>Wrong</th>
        <th>Points</th>
    </tr>
    {% for r in result %}
    <tr>
        <td>{{r.date}}</td>
        <td>{{r.time}}</td>
        <td>{{r.attempt}}</td>
        <td>{{r.right}}</td>
        <td>{{r.wrong}}</td>
        <td>{{r.points}}</td>
    </tr>
    {% endfor %}
</table>
<div class="bgre"></div>
{% endblock %}

project/myproject/OTS/templates/test_paper.html
{% extends 'main.html' %}

{% block title %} OTS - Test Paper {% endblock title %}
{% block top %}

{% endblock %}
{% block content %}
<form action="{% url 'OTS:calculateTest'  %}" method="post">
    {% csrf_token %}
    {% for question in questions %}
    <div class="question">
        <input type="hidden", name="qno{{question.qid}}" value="{{question.qid}}">
        {{question.que}}
    </div>
    <div class="options"><input type="radio" name="q{{question.qid}}" value="a">{{question.a}}</div>
    <div class="options"><input type="radio" name="q{{question.qid}}" value="b">{{question.b}}</div>
    <div class="options"><input type="radio" name="q{{question.qid}}" value="c">{{question.c}}</div>
    <div class="options"><input type="radio" name="q{{question.qid}}" value="d">{{question.d}}</div>
    {% endfor %}
    <div class="sub"><input type="submit" value="Submit"></div>
</form>
{% endblock %}

project/myproject/OTS/templates/welcome.html
{% extends 'main.html' %}

{% block title %} Welcome to Online Testing System {% endblock title %}
{% block top %}
<a href="{%url 'OTS:registrationForm' %}"> SignUp </a>
<a href="{%url 'OTS:login' %}">Login</a>
{% endblock %}
{% block content %}
<p class="para">
    <marquee>Welcome To Online Testing System</marquee>
</p>
<div class="bg-img"></div>
<section>
    <div class="first">
        <div class="left">
            <h1>What is an Online Testing System?</h1>
            <p>An online Testing system is the complete agenda of an online test that has multiple features and
                functionalities.
                The online Testing system uses online exam software through which the tests are created, conducted,
                and evaluated.
                This type of Testing system has multiple benefits few of them are that it eliminates the dependency
                on paper for the question and answer sheets,
                and eliminates any sort of manual workload which is too much in the case of an offline test.</p>
            <h1>How does the Online Testing System work?</h1>
            <p>In Online Testing System the entire steps involved in a paper-based test right from the beginning to
                the end are digitized with the use of online assessment software.
                Let’s read how each step is automated with the application of the online exam platform-</p>
            <h3>Creation of test</h3>
            <p>The administrator has multiple options to create an online test that is interactive as well as effective.
                The online test creation platform provides a variety of question types using which a
                objective, or MCQ-type test can be easily created. Also, the choice of questions can be done from an
                existing test library or the test creator can create an all-new set of questions by uploading them with
                just a click.</p>
            <h3>Conducting of test</h3>
            <p>Conducting a large-scale test is not an issue when it comes to online tests.
                Online exam software has the feature to accommodate even a large pool of students at once.
                The additional feature of “candidate management” increases the feasibility of conducting a test on a
                large group of candidates in a systematic manner. It allows the test taker to categorize the candidates
                in their respective groups and at the time of conducting the test,
                the test taker can assign individual tests to every group, conducting multiple tests at once.</p>
            <h3>Evaluation of test</h3>
            <p>The last and most important part of any test is its result,and report. The online Testing
                system provides a comprehensive report system that is highly accurate and instant. The software can
                instantly score the test paper according to the marks assigned by the test creator. Later, a test report
                is generated that provides scores on every subject, section, and question of the test.</p>
        </div>
    </div>
</section>
{% endblock %}